services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'sail-postgres:/var/lib/postgresql/data'
    networks:
      - sail
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
      interval: 10s
      retries: 5
      start_period: 30s

networks:
  sail:
    driver: bridge

volumes:
  sail-postgres:
    driver: local
